latex_template.pdf: latex_template.tex
	pdflatex latex_template.tex
	pdflatex latex_template.tex
	pdflatex latex_template.tex

bibtex_example.pdf: bibtex_example.tex bibtex_example.bib
	pdflatex bibtex_example.tex
	bibtex bibtex_example
	pdflatex bibtex_example.tex
	pdflatex bibtex_example.tex
